[package]
name = "app"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2024"

[features]
print_stdout = []
print_log = []
native = ["general_storage_static/file"]
web = ["getrandom/wasm_js", "general_storage_static/web"]

[dependencies]
general_storage_static = { version = "0.3", features = ["bincode", "json"] }
direction = "0.19"
chargrid = { version = "0.14", features = ["serialize"] }
rgb_int = "0.2"
perlin2 = { version = "0.2", features = ["serialize"] }
line_2d = "0.6"
coord_2d = "0.4"
grid_2d = "0.16"
game = { path = "../game" }
log = "0.4"
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.9"
rand_isaac = { version = "0.4", features = ["serde"] }
rand_xorshift = { version = "0.4", features = ["serde"] }
maplit = "1.0"
getrandom = "0.3"
bincode = "1.3"
